from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Mapping, Sequence

from mave.chemistry.reaction import Reaction
from mave.chemistry.route import SynthesisRoute
from mave.core.types import (
    EscalationContext,
    Feedback,
    FeedbackLevel,
    FeedbackQuery,
    ReactionCandidate,
)
from mave.core.utils import make_query_id
from mave.environment.state import RetroState

from .cache import FeedbackCache
from .cost import RelativeCostModel


# ============================================================
# Oracle context
# ============================================================


@dataclass(frozen=True, slots=True)
class OracleContext:
    """
    Information exposed to the surrogate oracle system.

    Parameters
    ----------
    state:
        Current retrosynthetic planning state.

    selected_index:
        Index of the frontier molecule currently considered.

    candidates:
        Candidate reactions generated by the single-step model.

    feedback_history:
        Feedback already acquired at lower hierarchy levels.

    route_alternatives:
        Optional partial-route alternatives for L3 route
        comparison.
    """

    state: RetroState

    selected_index: int

    candidates: tuple[Reaction, ...]

    feedback_history: tuple[Feedback, ...] = ()

    route_alternatives: tuple[
        SynthesisRoute,
        ...
    ] = ()

    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )

    def __post_init__(self) -> None:
        if not (
            0 <= self.selected_index
            < len(
                self.state.unsolved_molecules
            )
        ):
            raise IndexError(
                "selected_index is outside the "
                "state's unsolved-molecule list."
            )

    @property
    def selected_molecule(self):
        return self.state.unsolved_molecules[
            self.selected_index
        ]

    @property
    def state_id(self) -> str:
        return self.state.state_id

    # --------------------------------------------------------
    # Conversion to the policy-facing core representation
    # --------------------------------------------------------

    def to_escalation_context(
        self,
    ) -> EscalationContext:

        candidates = tuple(
            ReactionCandidate(
                product_smiles=(
                    reaction.product_smiles
                ),
                reactant_smiles=(
                    reaction.reactant_smiles
                ),
                single_step_score=(
                    0.0
                    if reaction.score is None
                    else float(
                        reaction.score
                    )
                ),
                template_id=(
                    reaction.template_id
                ),
                reaction_id=(
                    reaction.reaction_id
                ),
                metadata=dict(
                    reaction.metadata
                ),
            )
            for reaction
            in self.candidates
        )

        level = (
            FeedbackLevel.L0
            if not self.feedback_history
            else max(
                feedback.level
                for feedback
                in self.feedback_history
            )
        )

        return EscalationContext(
            state=self.state.to_core_state(),
            candidates=candidates,
            current_level=level,
            feedback_history=(
                self.feedback_history
            ),
            context_id=self.state_id,
        )


# ============================================================
# Backend output
# ============================================================


@dataclass(frozen=True, slots=True)
class BackendResult:
    """
    Standard output returned by surrogate backends.

    complexity_score:
        Optional normalized query-complexity score in [0, 1].
        It is used only for query-cost calculation.
    """

    content: Any

    complexity_score: float | None = None

    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )

    def __post_init__(self) -> None:
        if (
            self.complexity_score is not None
            and not (
                0.0
                <= self.complexity_score
                <= 1.0
            )
        ):
            raise ValueError(
                "complexity_score must lie in [0, 1]."
            )


# ============================================================
# Level-specific oracle interface
# ============================================================


class FeedbackOracle(ABC):
    """
    Abstract interface for one hierarchy level.

    Subclasses implement:
      L1 Structural
      L2 Evaluative
      L3 Comparative
      L4 Strategic
    """

    level: FeedbackLevel

    @property
    @abstractmethod
    def feedback_types(
        self,
    ) -> tuple[str, ...]:
        ...

    @abstractmethod
    def available_queries(
        self,
        context: OracleContext,
    ) -> tuple[FeedbackQuery, ...]:
        """
        Return legal query actions at this feedback level.
        """

    @abstractmethod
    def evaluate(
        self,
        context: OracleContext,
        query: FeedbackQuery,
    ) -> BackendResult:
        """
        Execute the surrogate backend.

        This method returns feedback content but does NOT assign
        acquisition cost. Cost is handled centrally by
        MultiFidelityOracleSystem.
        """

    # --------------------------------------------------------
    # Validation
    # --------------------------------------------------------

    def validate_query(
        self,
        query: FeedbackQuery,
    ) -> None:

        if query.level != self.level:
            raise ValueError(
                f"Query level {query.level} does not match "
                f"oracle level {self.level}."
            )

        if (
            query.feedback_type
            not in self.feedback_types
        ):
            raise ValueError(
                f"Unsupported feedback type "
                f"{query.feedback_type!r} for "
                f"{self.__class__.__name__}."
            )


# ============================================================
# Full hierarchy
# ============================================================


class MultiFidelityOracleSystem:
    """
    Coordinator over L1-L4 oracle implementations.

    Responsibilities:
      - expose queries from the requested hierarchy level
      - dispatch queries to the correct surrogate backend
      - compute acquisition cost
      - cache previously acquired feedback
      - charge zero additional cost for cached feedback
    """

    def __init__(
        self,
        *,
        oracles: Sequence[
            FeedbackOracle
        ],
        cost_model: RelativeCostModel,
        cache: FeedbackCache | None = None,
    ) -> None:

        by_level: dict[
            FeedbackLevel,
            FeedbackOracle,
        ] = {}

        for oracle in oracles:

            if oracle.level in by_level:
                raise ValueError(
                    f"Duplicate oracle for "
                    f"{oracle.level}."
                )

            by_level[
                oracle.level
            ] = oracle

        self.oracles = by_level

        self.cost_model = cost_model

        self.cache = (
            cache
            if cache is not None
            else FeedbackCache()
        )

    # --------------------------------------------------------
    # Query discovery
    # --------------------------------------------------------

    def available_queries(
        self,
        context: OracleContext,
        level: FeedbackLevel,
    ) -> tuple[FeedbackQuery, ...]:

        if level == FeedbackLevel.L0:
            return ()

        oracle = self.oracles.get(
            level
        )

        if oracle is None:
            return ()

        return oracle.available_queries(
            context
        )

    def available_next_queries(
        self,
        context: OracleContext,
        current_level: FeedbackLevel,
    ) -> tuple[FeedbackQuery, ...]:

        next_value = (
            int(current_level) + 1
        )

        if next_value > int(
            FeedbackLevel.L4
        ):
            return ()

        return self.available_queries(
            context,
            FeedbackLevel(
                next_value
            ),
        )

    # --------------------------------------------------------
    # Query execution
    # --------------------------------------------------------

    def query(
        self,
        context: OracleContext,
        query: FeedbackQuery,
    ) -> Feedback:

        oracle = self.oracles.get(
            query.level
        )

        if oracle is None:
            raise KeyError(
                f"No oracle registered for "
                f"{query.level}."
            )

        oracle.validate_query(
            query
        )

        query_id = (
            query.query_id
            or make_query_id(
                state_id=context.state_id,
                level=int(
                    query.level
                ),
                feedback_type=(
                    query.feedback_type
                ),
                payload=query.payload,
            )
        )

        # ----------------------------------------------------
        # Reuse cached feedback without additional cost.
        # ----------------------------------------------------

        cached = self.cache.get(
            query_id
        )

        if cached is not None:
            return Feedback(
                level=cached.level,
                feedback_type=(
                    cached.feedback_type
                ),
                content=cached.content,
                cost=0.0,
                query_id=query_id,
                cached=True,
                metadata={
                    **dict(
                        cached.metadata
                    ),
                    "original_cost": (
                        cached.cost
                    ),
                },
            )

        # ----------------------------------------------------
        # Surrogate evaluation
        # ----------------------------------------------------

        result = oracle.evaluate(
            context,
            query,
        )

        cost = self.cost_model.compute(
            query.feedback_type,
            complexity_score=(
                result.complexity_score
            ),
        )

        feedback = Feedback(
            level=query.level,
            feedback_type=(
                query.feedback_type
            ),
            content=result.content,
            cost=cost,
            query_id=query_id,
            cached=False,
            metadata=dict(
                result.metadata
            ),
        )

        self.cache.put(
            query_id,
            feedback,
        )

        return feedback

    # --------------------------------------------------------
    # Cache management
    # --------------------------------------------------------

    def clear_cache(self) -> None:
        self.cache.clear()